public with sharing class EmailValidationTriggerHandler extends TriggerHandler{
    protected override void beforeInsert(){
    }
  
  	protected override void beforeUpdate(){
    }
  
  	protected override void beforeDelete(){
        
    }
  
  	protected override void afterInsert(){
        
    }
  
  	protected override void afterUpdate(){
        
    }
  
  	protected override void afterDelete(){
        
    }
 
  	protected override void afterUndelete(){
        
    }
}